global:
  scrape_interval: 5s  # How often to scrape the metrics

scrape_configs:
  - job_name: 'optimize'
    static_configs:
      - targets: ['optimize:9099']  # This points to the optimize container on port 9099
